### ISSUE TITLE
Uncaught exception 'Exception' with message 'DateTimeZone::_

### ISSUE THREAD

**Issue by rigoy22k** [wlox/wlox#117]
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/html/wlox/frontend/lib/common.php:83\nStack trace:\n#0 /var/www/html/wlox/frontend/lib/common.php(83): DateTimeZone->__construct('')\n#1 /var/www/html/wlox/frontend/htdocs/index.php(2): include('/var/www/html/w...')\n#2 {main}\n  thrown in /var/www/html/wlox/frontend/lib/common.php on line 83

i just add manually on line 83:

date_default_timezone_set('America/Los_Angeles');
//$dtz = new DateTimeZone($CFG->default_timezone);
$dtz = new DateTimeZone('America/Los_Angeles');

**Comment by Guillerbr** [comment]
this must be configured in the administrative part.
or am I wrong?

**Comment by directoryio** [comment]
same error

Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct() [<a href='datetimezone.--construct'>datetimezone.--construct</a>]: Unknown or bad timezone ()' in C:\xampp\htdocs\frontend\lib\common.php:83 Stack trace: #0 C:\xampp\htdocs\frontend\lib\common.php(83): DateTimeZone->__construct('') #1 C:\xampp\htdocs\frontend\htdocs\index.php(2): include('C:\xampp\htdocs...') #2 {main} thrown in C:\xampp\htdocs\frontend\lib\common.php on line 83
